catalog/urls.py
from django.urls import path
from .import views

urlpatterns = [
        path('', views.index, name='index'),
        path('books/', views.BookListView.as_view(), name='books'),
        path('books/<int:pk>', views.BookDetailView.as_view(), name='book-detail'),
        path('authors/', views.AuthorListView.as_view(), name='authors'),
        path('author/<int:pk>', views.AuthorDetailView.as_view(), name='author-detail'),
        path('mybooks/', views.LoanedBooksByUserListView.as_view(), name='my-borrowed'),
        path('borrowers/', views.BorrowersListView.as_view(), name='borrowers'),
        path('book/<uuid:pk>/renew/', views.renew_book_librian, name='renew-book-librian'),
        path('author/create', views.AuthorCreate.as_view(), name='author_create'),
        path('author/<int:pk>/delete', views.AuthorDelete.as_view(), name='author_delete'),
        path('author/<int:pk>/update', views.AuthorUpdate.as_view(), name='author_update'),
        path('book/create', views.BookCreate.as_view(), name='book_create'),
        path('book/<int:pk>/delete', views.BookDelete.as_view(), name='book_delete'),
        path('book/<int:pk>/update', views.BookUpdate.as_view(), name='book_update'),
]

locallibrary/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
]

urlpatterns += [
        path('catalog/', include('catalog.urls')),
]

from django.conf import settings
from django.conf.urls.static import static
# Use static() to add url mapping to serve static files during development (only)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

#Add Django site authentication urls (for login, logout, password management)
urlpatterns += [
    path('accounts/', include('django.contrib.auth.urls')),
]

catalog/models.py
from django.db import models
from isbn_field import ISBNField
from django.urls import reverse #Used to generate URLs by reversing the URL patterns
import uuid
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.models import User
from datetime import date

# Create your models here.

class Genre(models.Model):
    """
    Model representing a book genre (e.g.g Science Fiction, Non Fiction).
    """
    name = models.CharField(max_length=200, help_text="enter a book genre (e.g. Science Fiction, French Poety etc.)")

    def __str__(self):
        """
        String for representing the Model object (in Admin site etc.)
        """
        return self.name

class Language(models.Model):
    """
    Model representing language of book
    """
    name = models.CharField(max_length=100, unique=True)

    def __str__(self):
        return self.name

class Book(models.Model):
    """
    Model representing a book (but not a specific copy of book).
    """
    title = models.CharField(max_length=200)
    author = models.ForeignKey('Author', on_delete=models.SET_NULL, null=True)
    # ForeignKey used because book can only have one author, but authors can have multiple books
    # Author as a string rather than object because it hasn't been declared yet in the file.
    summary = models.TextField(max_length=2000, help_text="Enter a brief description of the book")
    isbn = ISBNField(clean_isbn=False,help_text='13 Character <a href="https://www.isbn-international.org/content/what-isbn">ISBN number</a>')
    genre = models.ManyToManyField(Genre, help_text="Select a genre for this book")
    # ManyToManyField used because genre can contain many books. Book can cover many genres.
    # Genre class has already been defined so we can specify the object above.
    language = models.ForeignKey('Language', on_delete=models.SET_NULL, null=True, blank=True)

    def __str__(self):
        """
        String for representing the Model object.
        """
        return self.title

    def get_absolute_url(self):
        """
        Return the url to access a particular book instance.
        """
        return reverse('book-detail', args=[str(self.id)])

    def display_genre(self):
        """
        Creates a sting for the Genre. This is required for display genre in Admin
        """
        return ', '.join([ genre.name for genre in self.genre.all()[:3] ])

    class Meta:
        ordering = ['pk']

class BookInstance(models.Model):
    """
    Model representing a specify copy of book (i.e. that can be borrowed from the library).
    """
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, help_text="Unique ID for this particular book across whole library")
    book = models.ForeignKey('Book', on_delete=models.SET_NULL, null=True)
    imprint = models.CharField(max_length=200)
    due_back = models.DateField(null=True, blank=True, help_text="Book return date")
    borrower = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True)

    LOAN_STATUS = [
            ('m', 'Maintenance'),
            ('o', 'On loan'),
            ('a', 'Available'),
            ('r', 'Reserved'),
    ]

    status = models.CharField(max_length=1, choices=LOAN_STATUS, blank=True, default='m', help_text="Book availablity")

    class Meta:
        ordering = ['due_back']
        permissions = (('can_mark_returned', 'Set book as returned'),)

    """
    String for representing book.title, status, due back and id
    """
    def __str__(self):
        #human_status = ''.join([s[1] for s in self.LOAN_STATUS if s[0] == self.status])
        return "{0}, [{1}], {2}, {3}".format(self.book.title, self.get_status_display(),
            self.due_back, self.id
    )

    @property
    def is_overdue(self):
        if self.due_back and date.today() > self.due_back:
            return True
        return False

class Author(models.Model):
    """
    Model representing an author
    """
    first_name = models.CharField(max_length=200)
    last_name = models.CharField(max_length=200)
    date_of_birth = models.DateField(null=True, blank=True)
    date_of_death = models.DateField('Died', null=True, blank=True)

    def get_absolute_url(self):
        """
        Returns the url to access a particular author instance
        """
        return reverse('author-detail', args=[str(self.id)])

    def __str__(self):
        return "{0}, {1}".format(self.first_name, self.last_name)

    class Meta:
        ordering = ['pk']

catalog/forms.py
import datetime

from django import forms
from django.core.exceptions import ValidationError
from django.utils.translation import ugettext_lazy as _

from django.forms import ModelForm

from catalog.models import BookInstance, Book

class RenewBookModelForm(ModelForm):
    class Meta:
        model = BookInstance
        fields = ['due_back']
        labels = {'due_back': _('New renewal date')}
        help_texts = {'due_back': _('Enter a date between now and 4 weeks (default is 3).')}

    def clean_due_back(self):
        date = self.cleaned_data.get('due_back', 0)

        if not date:
            raise ValidationError(_('Invalid date - invalid value'))

        if date < datetime.date.today():
            raise ValidationError(_('Invalid date - renewal in past'))

        if date > (datetime.date.today() + datetime.timedelta(weeks=4)):
            raise ValidationError(_('Invalid date - renewal date more than 4 weeks ahead'))

        return date

    """

        def clean_title(self):
            title = self.cleaned_data['title']
            return title

        def clean_author:
            author = self.cleaned_data['author']
            return author

        def clean_summary:
            summary = self.cleaned_data['summary']
            return summary

        def clean_isbn:
            isbn = self.cleaned_data['isbn']
            return isbn

        def clean_genre:
            genre = self.cleaned_data['genre']
            return genre

class BookForm(ModelForm):
    class Meta:
        model = Book
        fields = ['title', 'author', 'summary', 'isbn', 'genre', 'language']
"""

catalog/views.py
import datetime

from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse
from .models import Book, BookInstance, Author
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.mixins import PermissionRequiredMixin
from django.contrib.auth.decorators import permission_required
from django.http import HttpResponseRedirect
from django.urls import reverse
from catalog.forms import RenewBookModelForm

def index(request):
    """
    Function for representing home pate
    """
    # Number of visits to this view, as counted in the session variable.
    num_visits=request.session.get('num_visits', 0)
    request.session['num_visits'] = num_visits+1

    data = {}
    data['num_books'] = Book.objects.all().count()
    data['num_instances'] = BookInstance.objects.all().count()
    data['num_instances_available'] = BookInstance.objects.filter(status__exact='a').count()
    data['num_authors'] = Author.objects.count()
    data['num_books_title_filter'] = Book.objects.filter(title__contains='world').count()
    data['num_books_genre_filter'] = Book.objects.filter(genre__name__contains='fiction').distinct().count()
    data['num_visits'] = num_visits


    return render(
            request,
            'index.html',
            context={'data': data}
    )


from django.views import generic

class BookListView(generic.ListView):
    model = Book
    context_object_name = 'book_list'
    paginate_by = 10

class BookDetailView(generic.DetailView):
    model = Book

class AuthorListView(generic.ListView):
    model = Author
    paginate_by = 10

class AuthorDetailView(generic.DetailView):
    model = Author
    paginate_by = 5

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        pk = self.kwargs.get('pk', None)
        if pk is not None:
            books = Book.objects.filter(author_id=pk)
            paginator = Paginator(books, self.paginate_by)
            page = self.request.GET.get('page', 1)

            try:
                page_obj = paginator.page(page)
            except PageNotAnInteger:
                page_obj = paginator.page(1)
            except EmptyPage:
                page_obj = paginator.page(paginator.num_pages)

            context['page_obj'] = page_obj
            context['book_list'] = context['page_obj']
            context['is_paginated'] = paginator.num_pages > 1 or None
        return context

class LoanedBooksByUserListView(LoginRequiredMixin, generic.ListView):
    """Generic class-based view listing books on loan to current user."""
    model = BookInstance
    paginate_by = 10
    template_name = 'catalog/bookinstance_list_boorowed_books.html'

    def get_queryset(self):
        return BookInstance.objects.filter(borrower=self.request.user).filter(status__exact='o').order_by('due_back')


#from django.contrib.admin.views.decorators import staff_member_required

class BorrowersListView(PermissionRequiredMixin, generic.ListView):
    model = BookInstance
    permission_required = ('catalog.can_mark_returned')
    template_name = 'catalog/bookinstance_list_borrowers.html'

@permission_required('catalog.can_mark_returned')
def renew_book_librian(request, pk):
    bookinstance = get_object_or_404(BookInstance, pk=pk)

    # If this is a POST request then process the Form data

    if request.method == 'POST':
        form = RenewBookModelForm(request.POST)
        if form.is_valid():
            bookinstance.due_back = form.cleaned_data['due_back']
            bookinstance.save()
            return HttpResponseRedirect(reverse('borrowers'))

    else:
        proposed_renewal_date = datetime.date.today() + datetime.timedelta(weeks=3)
        form = RenewBookModelForm(
            initial={'due_back': proposed_renewal_date}
        )

    context = {
        'form': form,
        'bookinstance': bookinstance,
    }
    return render(
        request, 'catalog/book_renew_librian.html', context
    )


from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.urls import reverse_lazy

from catalog.models import Author

class AuthorCreate(PermissionRequiredMixin, CreateView):
    permission_required = ('catalog.add_author')
    model = Author
    fields = ['first_name', 'last_name', 'date_of_birth', 'date_of_death']
    initial = {
        'date_of_death': '05/11/2018',
    }

class AuthorUpdate(UpdateView):
    permission_required = ('catalog.change_author')
    model = Author
    fields = ['first_name', 'last_name', 'date_of_birth', 'date_of_death']

class AuthorDelete(DeleteView):
    permission_required = ('catalog.delete_author')
    model = Author
    success_url = reverse_lazy('authors')

class BookCreate(PermissionRequiredMixin, CreateView):
    permission_required = ('catalog.add_book')
    model = Book
    fields = ['title', 'author', 'summary', 'isbn', 'genre', 'language']
    success_url = reverse_lazy('books')

class BookUpdate(PermissionRequiredMixin, UpdateView):
    permission_required = ('catalog.change_book')
    model = Book
    fields = ['title', 'author', 'summary', 'isbn', 'genre', 'language']
    success_url = reverse_lazy('books')

class BookDelete(PermissionRequiredMixin, DeleteView):
    permission_required = ('catalog.delete_book')
    model = Book
    success_url = reverse_lazy('books')

catalog/templates/catalog/author_confirm_delete.html
{% extends 'base_generic.html' %}
{% block content %}
<h1>Delete author</h1>
<p>Are you sure to delete the author: {{author}}?</p>
<form action="" method="POST">
    {% csrf_token %}
    <input type="submit" class="btn btn-primary" value="Yes, delete"/>
    <a class="btn btn-secondary" role="button" href="{{ request.META.HTTP_REFERER }}">Take me back</a>
</form>
{% endblock %}

catalog/templates/catalog/author_detail.html
{% extends 'base_generic.html' %}
{% block title %}
<title>Local Library[{{ author }}]</title>
{% endblock %}
{% block content %}
<h1>Author: {{ author }}</h1>
<p><strong>First name:</strong> {{ author.first_name }}
<p><strong>Last name:</strong> {{ author.last_name }}
<p>
    <strong>Date of birth:</strong>
    {% if author.date_of_birth is None %} &mdash;
    {% else %} {{ author.date_of_birth }}
    {% endif %}
</p>
<p>
    <strong>Date of death:</strong>
    {% if author.date_of_death is None %} &mdash;
    {% else %} {{ author.date_of_death}}
    {% endif %}

{% if perms.catalog.change_author %}
<p>
<a href="{% url 'author_update' author.pk %}" class="btn btn-primary" role="button">update</a>
{% endif %}
{% if perms.catalog.delete_author %}
<a href="{% url 'author_delete' author.pk %}" class="btn btn-warning" role="button">delete</a>
{% endif %}
</p>
<div class="author_detail_books">
    {% if book_list %}
        <h2>Books:</h2>
        {% for book in book_list %}
        <p><a href="{{ book.get_absolute_url }}">{{ book.title }}</a></p>
        {% endfor %}
    {% else %}
        <h2>{{ author }} doesn't have any books in library</h2>
    {% endif %}
</div>
{% endblock %}

catalog/templates/catalog/author_form.html
{% extends 'base_generic.html' %}
{% block content %}
<form action="" method="POST">
    {% csrf_token %}
    {{ form.as_p}}
    <input type="submit" value="Submit"/>
</form>
{% endblock %}

catalog/templates/catalog/author_list.html
{% extends 'base_generic.html' %}
{% block title %}
<title>Local Library[Authors]</title>
{% endblock %}
{% block content %}
{% if author_list %}
    <h1>Author list</h1>
    {% for author in author_list %}
    <li>
        <a href="{{ author.get_absolute_url }}">
            {{ author }}
        </a>
        {% if author.date_of_birth is not None %}
        ({{ author.date_of_birth }} &mdash; {% if author.date_of_death %}{{ author.date_of_death }} {% endif %})
        {% endif %}
        {% if perms.catalog.change_author %}
        <a href="{% url 'author_update' author.pk%}">edit</a>
        {% endif %}
        {% if perms.catalog.delete_author %}
        | <a href="{% url 'author_delete' author.pk%}">delete</a>
        {% endif %}
    </li>
    {% endfor %}
    {% if perms.catalog.add_author %}
    <p>
        <a role="button" class="btn btn-primary"
            href="{% url 'author_create' %}">Add author</a>
    </p>
    {% endif %}
{% else %}
    <h1>No authors here</h1>
{% endif %}
{% endblock %}

catalog/templates/catalog/book_confirm_delete.html
{% extends 'base_generic.html' %}
{% block content %}
<h1>Delete book</h1>
<p>Are you sure to delete the book: {{ book  }}?</p>
<form action="" method="POST">
    {% csrf_token %}
    <input type="submit" class="btn btn-primary" value="Yes, delete"/>
    <a class="btn btn-secondary" role="button" href="{{ request.META.HTTP_REFERER }}">Take me back</a>
</form>
{% endblock %}

catalog/templates/catalog/book_detail.html
{% extends 'base_generic.html' %}
{% block title %}
<title>Local Library[{{ book.title }}]</title>
{% endblock %}
{% block content %}
<h1>Title: {{ book.title }}</h1>
{% if book.author %}
<p><strong>Author:</strong> <a href="{% url 'author-detail' book.author.pk %}">{{ book.author }}</a></p>
{% endif %}
<p><strong>Summary:</strong> {{ book.summary }}</p>
<p><strong>ISBN:</strong> {{ book.isbn}}</p>
<p><strong>Language:</strong> {{ book.language}}</p>
<p><strong>Genre:</strong> {% for genre in book.genre.all %} {{ genre }}
{% if not forloop.last %}, {% endif %}{% endfor %} </p>
<div class="book_detail_copies">
    <h4>Copies:</h4>
    {% for copy in book.bookinstance_set.all %}
    <hr/>
    <p class="
        {% if copy.status == 'a' %} text-success
        {% elif copy.status == 'd' %} text-danger
        {% else %} text-warning
        {% endif %}">{{ copy.get_status_display }}</p>
    {% if copy.status != 'a' %}
    <p><strong>Due to retunred:</strong> {{ copy.due_back }}</p>
    {% endif %}
    <p><strong>Imprint:</strong> {{ copy.imprint }}
    <p class="text-muted"><strong>Id:<strong> {{ copy.id }}</p>
    {% endfor %}
</div>
{% endblock %}

catalog/templates/catalog/book_form.html
{% extends 'base_generic.html' %}
{% block content %}
<form action="" method="POST">
    {{ form.non_field_errors }}
    {% csrf_token %}
    <div class="form-group row">
        {{ form.title.errors }}
        {{ form.title.label_tag }}
        {{ form.title}}
    </div>
    <div class="form-group row">
        {{ form.author.errors }}
        {{ form.author.label_tag }}
        {{ form.author}}
    </div>
    <div class="form-group row">
        {{ form.summary.errors }}
        {{ form.summary.label_tag }}
        {{ form.summary}}
    </div>
    <div class="form-group row">
        {{ form.isbn.errors }}
        {{ form.isbn.label_tag }}
        {{ form.isbn}}
    </div>
    <div class="form-group row">
        {{ form.genre.errors }}
        {{ form.genre.label_tag }}
        {{ form.genre}}
    </div>
    <div class="form-group row">
        {{ form.language.errors }}
        {{ form.language.label_tag }}
        {{ form.language}}
    </div>
    <input type="submit" class="btn btn-primary" value="Submit"/>
</form>
{% endblock %}

catalog/templates/catalog/book_list.html
{% extends 'base_generic.html' %}
{% block title %}
<title>Local Library[Books list]</title>
{% endblock %}
{% block content %}
<h1>Book List</h1>
{% if book_list %}
<ul>
    {% for book in book_list %}
    <li>
        <a href="{{ book.get_absolute_url }}">
            {{ book.title }}
        </a> 
        {{ book.author }} ({{ book.display_genre }})
        {% if perms.catalog.change_book %}
        <a href="{% url 'book_update' book.pk %}">edit</a>
        {% endif %}
        {% if perms.catalog.delete_book %}
        | <a href="{% url 'book_delete' book.pk %}">delete</a>
        {% endif %}
    </li>
    {% endfor %}
</ul>
{% else %}
<p>There are no books in the library.</p>
{% endif %}
{% endblock %}

catalog/templates/catalog/book_renew_librian.html
{% extends 'base_generic.html' %}
{% block title %}
<title>Local Library[Book Renew Librian]</title>
{% endblock %}
{% block content %}
    <h1>Renew: {{ bookinstance.book.title }}</h1>
    <p>Borrowed: {{ bookinstance.borrower }}</p>
    <p {% if bookinstance.is_overdue %}class="text_danger"{% endif %}>
        Due date: {{ bookinstance.due_back }}
    </p>
    <form action="" method="POST">
        {% csrf_token %}
            {{ form.as_p}}
        <input type="submit" value="Submit"/>
    </form>
{% endblock %}

catalog/templates/catalog/bookinstance_list_boorowed_books.html
{% extends 'base_generic.html' %}
{% block title %}
<title>Local Library[My borrowed books]</title>
{% endblock %}
{% block content %}
{% if bookinstance_list %}
    <h1>My borrowed books</h1>
    <ul>
    {% for bookinstance in bookinstance_list %}
        <li class="{% if bookinstance.is_overdue %}text-danger{% endif %}">
            <a href="{% url 'book-detail' bookinstance.book.pk %}">{{ bookinstance.book.title }}</a> due back - {{ bookinstance.due_back }}
        </li>
    {% endfor %}
    </ul>
{% else %}
    <h1>You dont have any books here</h1>
{% endif %}
{% endblock %}

catalog/templates/catalog/bookinstance_list_borrowers.html
{% extends 'base_generic.html' %}
{% block content %}
{% if bookinstance_list%}
<h1>All borrowed books</h1>
<ul>
{% for bookinstance in bookinstance_list %}
<li class="{% if bookinstance.is_overdue %}text-danger {% endif %}">
    <a href="{% url 'book-detail' bookinstance.book.pk %}">{{bookinstance.book.title}}</a> ({{bookinstance.due_back}}) {{bookinstance.borrower}}
    {% if perms.catalog.can_mark_returned %}- <a href="{% url 'renew-book-librian' bookinstance.id %}">Renew</a>  {% endif %}
</li>
{% endfor %}
</ul>
{% else %}
<h1>You dont have any borrowers</h1>
{% endif %}
{% endblock %}